import type { DemoScript } from '@/types/demo.types';

export const customersScript: DemoScript = {
  name: 'Gestión de Clientes',
  description: 'Demostración de búsqueda, creación y gestión de clientes',
  steps: [
    { type: 'say', message: 'Gestionemos clientes', duration: 2000 },
    { type: 'navigate', route: '/customers' },
    { type: 'waitFor', selector: '[data-tour="customer-search"]', timeout: 5000 },
    { type: 'click', selector: '[data-tour="customer-search"]', timeout: 5000 },
    { type: 'type', selector: '[data-tour="customer-search"]', text: 'Juan', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour^="customer-row-"]', timeout: 5000 },
    { type: 'click', selector: '[data-tour^="customer-row-"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="customer-detail"]', timeout: 5000 },
    { type: 'say', message: 'Aquí puedes ver los detalles del cliente', duration: 2000 },
    { type: 'click', selector: '[data-tour="customer-tab-history"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="purchase-history"]', timeout: 5000 },
    { type: 'say', message: 'Historial de compras del cliente', duration: 2000 },
    { type: 'click', selector: '[data-tour="customer-tab-summary"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="customer-summary"]', timeout: 5000 },
    { type: 'say', message: 'Resumen de compras por producto', duration: 2000 },
    { type: 'click', selector: '[data-tour="customer-tab-info"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="customer-tab-info"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="renew-subscription"]', timeout: 5000 },
    { type: 'click', selector: '[data-tour="renew-subscription"]', timeout: 5000 },
    { type: 'waitFor', selector: '.modal-overlay', timeout: 3000 },
    { type: 'click', selector: '.modal-close', timeout: 3000 },
    { type: 'click', selector: '[data-tour="back-to-customers"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="customers-list"]', timeout: 5000 },
    { type: 'click', selector: '[data-tour="create-customer"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="customer-name-input"]', timeout: 5000 },
    { type: 'click', selector: '[data-tour="customer-name-input"]', timeout: 5000 },
    { type: 'type', selector: '[data-tour="customer-name-input"]', text: 'Cliente Demo', timeout: 5000 },
    { type: 'click', selector: '[data-tour="customer-phone-input"]', timeout: 5000 },
    { type: 'type', selector: '[data-tour="customer-phone-input"]', text: '+54 11 1234-5678', timeout: 5000 },
    { type: 'click', selector: '[data-tour="customer-pin-input"]', timeout: 5000 },
    { type: 'type', selector: '[data-tour="customer-pin-input"]', text: '12AB', timeout: 5000 },
    { type: 'select', selector: '[data-tour="customer-subscription-type"]', value: 'MONTHLY', timeout: 5000 },
    { type: 'click', selector: '[data-tour="customer-subscription-price"]', timeout: 5000 },
    { type: 'type', selector: '[data-tour="customer-subscription-price"]', text: '50.00', timeout: 5000 },
    { type: 'click', selector: '[data-tour="customer-notes-input"]', timeout: 5000 },
    { type: 'type', selector: '[data-tour="customer-notes-input"]', text: 'Cliente de demostración', timeout: 5000 },
    { type: 'say', message: 'En modo demo, este cliente no se guardará realmente', duration: 2000 },
    { type: 'click', selector: '[data-tour="cancel-customer"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="customers-list"]', timeout: 5000 },
    { type: 'say', message: 'Demo de clientes completada', duration: 2000 },
  ],
};
