import type { DemoScript } from '@/types/demo.types';

export const salesNewScript: DemoScript = {
  name: 'Nueva Venta',
  description: 'Demostración del flujo de creación de venta',
  steps: [
    { type: 'say', message: 'Vamos a hacer una venta en 20 segundos 😎', duration: 2000 },
    { type: 'navigate', route: '/sales/new' },
    { type: 'waitFor', selector: '[data-tour="customer-search-input"]', timeout: 5000 },
    { type: 'click', selector: '[data-tour="customer-search-input"]', timeout: 5000 },
    { type: 'type', selector: '[data-tour="customer-search-input"]', text: 'Juan', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour^="customer-row-"]', timeout: 5000 },
    { type: 'click', selector: '[data-tour^="customer-row-"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="product-search-input"]', timeout: 5000 },
    { type: 'click', selector: '[data-tour="product-search-input"]', timeout: 5000 },
    { type: 'type', selector: '[data-tour="product-search-input"]', text: 'Premium', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour^="product-row-"]', timeout: 5000 },
    { type: 'click', selector: '[data-tour^="product-row-"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="grams-input"]', timeout: 5000 },
    { type: 'click', selector: '[data-tour="grams-input"]', timeout: 5000 },
    { type: 'type', selector: '[data-tour="grams-input"]', text: '1.5', timeout: 5000 },
    { type: 'click', selector: '[data-tour="add-product"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour^="ticket-item-"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="change"]', timeout: 5000 },
    { type: 'assert', selector: '[data-tour="change"]', contains: '€', timeout: 5000 },
    { type: 'click', selector: '[data-tour="cash-given-input"]', timeout: 5000 },
    { type: 'type', selector: '[data-tour="cash-given-input"]', text: '50', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="confirm-sale"]', timeout: 5000 },
    { type: 'click', selector: '[data-tour="confirm-sale"]', timeout: 5000 },
    { type: 'waitFor', selector: '[data-tour="sale-success-modal"]', timeout: 5000 },
    { type: 'say', message: 'Venta #123 creada ✅', duration: 2000 },
  ],
};
